### ISSUE TITLE
missing upload_forum.php

### ISSUE THREAD

**Issue by driftypuddle** [hedii/Codeigniter-Forum#5]
hello missing upload_forum.php

**Comment by hedii** [comment]
hi @driftypuddle 
i don't understand, what is missing?

**Comment by driftypuddle** [comment]
when upload a image it says Unable to load the requested file: upload_forum.php
in edit profile

**Comment by hedii** [comment]
have you made modifications on the code?

There is no "upload_forum" word in this repo.

the only place where you might have change something that give this error is here: https://github.com/hedii/Codeigniter-Forum/blob/master/application/controllers/User.php#L373

Have you change upload_form to upload_forum?
keep upload_form instead of upload_forum if you changed it and that should be ok.
let me know.

**Comment by driftypuddle** [comment]
Unable to load the requested file: upload_form.php
same thing

**Comment by hedii** [comment]
have you made modifications on the code?

**Comment by driftypuddle** [comment]
will post bin the code 2 secs

**Comment by driftypuddle** [comment]
http://pastebin.com/nCdDc8JY

**Comment by hedii** [comment]
@driftypuddle i just tested a fresh install and everything is ok, even the avatar upload.
You have to check every modifications you made, or restart with a fresh install.
sorry but i have no time to read your code snippet and find midifications (and the error is saying it cannot find the view file for upload form, so the problem may not be in the user controller file).
good luck, i close this issue for now.
